name: 'Wait for other action'
description: 'Simple action to wait for other action'
author: 'Khachatur Ashotyan'
inputs:
  token:
    required: true
    description: 'Your GitHub token'
  workflow:
    required: true
    description: 'File name of the workflow you wanna wait for'
  interval:
    description: 'The interval between workflow checks (default is 3s)'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'clock'
  color: 'gray-dark'   
